import XCTest
@testable import Core

final class ScobyProviderTests: XCTestCase {
    func testScobyProviderId() {
        let provider = ScobyProvider()
        XCTAssertEqual(provider.id, "scoby")
        XCTAssertEqual(provider.dependencyId, "scoby")
    }

    func testScobyProviderCheckStatus() async throws {
        let provider = ScobyProvider()
        let status = try await provider.checkStatus()
        XCTAssertEqual(status, .ready)
    }

    func testScobyProviderFetchHealthObservations() async throws {
        let provider = ScobyProvider()
        let observations = try await provider.fetchHealthObservations(for: Date())

        // Should return an array (may be empty if no logs found)
        XCTAssertNotNil(observations)
        XCTAssertTrue(observations is [String])
    }

    func testScobyProviderGenerateMarkdownReport() async throws {
        let provider = ScobyProvider()
        let report = try await provider.generateMarkdownReport(for: Date())

        // Should contain expected headers
        XCTAssertTrue(report.contains("# SCOBY System Health Report"))
        XCTAssertTrue(report.contains("**Date:**"))
        XCTAssertTrue(report.contains("**Generated:**"))
        XCTAssertTrue(report.contains("*Report generated by SCOBY Provider*"))
    }
}
