import Foundation

/// Provider for SCOBY system health data.
///
/// SCOBY (System COmponent BYstem) provides insights into:
/// - Log file analysis (errors, warnings, anomalies)
/// - System health metrics
/// - Recent activity snapshots
///
/// This provider scans configurable directories for logs and error files,
/// then generates structured health reports that can be consumed by Briefly.
public struct ScobyProvider: Provider {
    public let id = "scoby"
    public let dependencyId = "scoby"  // Internal provider, no external dependency
    private let executor = ShellExecutor()

    // MARK: - Configuration

    /// Default log directories to scan
    private let defaultLogPaths = [
        "./logs",                     // Project-relative logs
        "~/Library/Logs",             // macOS user logs
        "/var/log",                   // System logs (requires root)
    ]

    /// File patterns that indicate errors or issues
    private let errorFilePatterns = [
        "*error*.log",
        "*fatal*.log",
        "*exception*.log",
        "*crash*.log",
    ]

    /// Warning-level file patterns
    private let warningFilePatterns = [
        "*warning*.log",
        "*warn*.log",
    ]

    public init() {}

    // MARK: - Provider Protocol

    public func checkStatus() async throws -> ProviderStatus {
        // SCOBY is an internal provider with no external dependencies
        // It's always ready, but may have limited data based on filesystem access
        return .ready
    }

    // MARK: - Data Fetching

    /// Collect system health data for analysis.
    ///
    /// This method:
    /// 1. Scans log directories for recent entries
    /// 2. Identifies error and warning patterns
    /// 3. Generates a structured health report
    ///
    /// - Parameter date: The date to analyze (defaults to today)
    /// - Returns: Array of structured health observation strings
    public func fetchHealthObservations(for date: Date) async throws -> [String] {
        let status = try await checkStatus()
        guard case .ready = status else {
            throw ProviderError.notReady(status)
        }

        var observations: [String] = []

        // Scan for recent errors
        let errorObservations = try await scanForErrors(on: date)
        observations.append(contentsOf: errorObservations)

        // Scan for warnings
        let warningObservations = try await scanForWarnings(on: date)
        observations.append(contentsOf: warningObservations)

        // Check log file sizes for growth anomalies
        let sizeObservations = try await checkLogFileGrowth(on: date)
        observations.append(contentsOf: sizeObservations)

        // Scan for crash reports
        let crashObservations = try await scanForCrashReports(on: date)
        observations.append(contentsOf: crashObservations)

        return observations
    }

    /// Generate a comprehensive SCOBY report in markdown format.
    ///
    /// - Parameter date: The date to analyze
    /// - Returns: Formatted markdown report
    public func generateMarkdownReport(for date: Date) async throws -> String {
        let observations = try await fetchHealthObservations(for: date)

        var report = "# SCOBY System Health Report\n\n"
        report += "**Date:** \(DateFormatter.yyyyMMdd.string(from: date))\n"
        report += "**Generated:** \(ISO8601DateFormatter().string(from: Date()))\n\n"

        // Deduplicate observations while preserving order
        let uniqueObservations = Array(Set(observations)).sorted()

        if uniqueObservations.isEmpty {
            report += "✅ No health issues detected.\n"
        } else {
            // Categorize observations
            let errors = uniqueObservations.filter { $0.contains("❌") }
            let warnings = uniqueObservations.filter { $0.contains("⚠️") }
            let info = uniqueObservations.filter { !$0.contains("❌") && !$0.contains("⚠️") }

            if !errors.isEmpty {
                report += "## ❌ Errors\n\n"
                errors.forEach { report += "- \($0)\n" }
                report += "\n"
            }

            if !warnings.isEmpty {
                report += "## ⚠️ Warnings\n\n"
                warnings.forEach { report += "- \($0)\n" }
                report += "\n"
            }

            if !info.isEmpty {
                report += "## ℹ️ System Observations\n\n"
                info.forEach { report += "- \($0)\n" }
                report += "\n"
            }
        }

        // Add metadata
        report += "---\n"
        report += "*Report generated by SCOBY Provider*\n"

        return report
    }

    // MARK: - Private Scanning Methods

    /// Scan for error patterns in log files.
    private func scanForErrors(on date: Date) async throws -> [String] {
        var findings: [String] = []

        for logPath in defaultLogPaths {
            let expandedPath = NSString(string: logPath).expandingTildeInPath
            guard let fileURL = URL(string: "file://\(expandedPath)") else { continue }

            let exists = await fileExists(at: fileURL)
            guard exists else { continue }

            // Check for error pattern files
            for pattern in errorFilePatterns {
                do {
                    let files = try await findFiles(in: expandedPath, matching: pattern)
                    for file in files {
                        let fileURL = URL(fileURLWithPath: "\(expandedPath)/\(file)")
                        let content = try? String(contentsOf: fileURL, encoding: .utf8)
                        let errorLines = content?.components(separatedBy: .newlines).filter { line in
                            line.localizedCaseInsensitiveContains("error") ||
                            line.localizedCaseInsensitiveContains("fatal") ||
                            line.localizedCaseInsensitiveContains("exception")
                        } ?? []

                        if !errorLines.isEmpty {
                            findings.append("❌ Found \(errorLines.count) error(s) in `\(file)`")
                        }
                    }
                } catch {
                    // Ignore permission errors for system directories
                    continue
                }
            }
        }

        return findings
    }

    /// Scan for warning patterns in log files.
    private func scanForWarnings(on date: Date) async throws -> [String] {
        var findings: [String] = []

        for logPath in defaultLogPaths {
            let expandedPath = NSString(string: logPath).expandingTildeInPath

            for pattern in warningFilePatterns {
                do {
                    let files = try await findFiles(in: expandedPath, matching: pattern)
                    for file in files {
                        findings.append("⚠️ Warning log file detected: `\(file)`")
                    }
                } catch {
                    continue
                }
            }
        }

        return findings
    }

    /// Check for unusual log file growth.
    private func checkLogFileGrowth(on date: Date) async throws -> [String] {
        var observations: [String] = []

        // Focus on project logs directory
        let projectLogsPath = "./logs"
        guard FileManager.default.fileExists(atPath: projectLogsPath) else {
            return observations
        }

        do {
            let files = try FileManager.default.contentsOfDirectory(atPath: projectLogsPath)
            for file in files where file.hasSuffix(".log") || file.hasSuffix(".json") {
                let fileURL = URL(fileURLWithPath: "\(projectLogsPath)/\(file)")
                let attributes = try FileManager.default.attributesOfItem(atPath: fileURL.path)

                if let fileSize = attributes[.size] as? UInt64 {
                    // Convert to human-readable size
                    let sizeMB = Double(fileSize) / (1024 * 1024)

                    if sizeMB > 10 {
                        observations.append("ℹ️ Large log file: `\(file)` (\(String(format: "%.2f", sizeMB)) MB)")
                    }
                }

                // Check modification date
                if let modDate = attributes[.modificationDate] as? Date {
                    let daysSinceModified = Calendar.current.dateComponents([.day], from: modDate, to: Date()).day ?? 0
                    if daysSinceModified <= 1 {
                        observations.append("ℹ️ Recently modified: `\(file)` (today)")
                    }
                }
            }
        } catch {
            // Ignore errors
        }

        return observations
    }

    /// Scan for crash reports in standard locations.
    private func scanForCrashReports(on date: Date) async throws -> [String] {
        var findings: [String] = []

        let crashPaths = [
            "~/Library/Logs/DiagnosticReports",
            "~/Library/Logs/CrashReporter",
        ]

        var allTodayFiles: [String] = []

        for crashPath in crashPaths {
            let expandedPath = NSString(string: crashPath).expandingTildeInPath
            guard let fileURL = URL(string: "file://\(expandedPath)") else { continue }

            let exists = await fileExists(at: fileURL)
            guard exists else { continue }

            do {
                let files = try FileManager.default.contentsOfDirectory(atPath: expandedPath)
                let todayFiles = files.filter { file in
                    let fileURL = URL(fileURLWithPath: "\(expandedPath)/\(file)")
                    guard let attributes = try? FileManager.default.attributesOfItem(atPath: fileURL.path),
                          let modDate = attributes[.modificationDate] as? Date else {
                        return false
                    }
                    return Calendar.current.isDateInToday(modDate)
                }
                allTodayFiles.append(contentsOf: todayFiles)
            } catch {
                continue
            }
        }

        // Combine all crash reports into a single entry
        if !allTodayFiles.isEmpty {
            let uniqueFiles = Array(Set(allTodayFiles)).sorted()
            let fileList = uniqueFiles.map { "\n  - \($0)" }.joined()
            findings.append("❌ Found \(uniqueFiles.count) crash report(s) from today:\(fileList)")
        }

        return findings
    }

    // MARK: - Helper Methods

    /// Check if a file or directory exists.
    private func fileExists(at url: URL) async -> Bool {
        return FileManager.default.fileExists(atPath: url.path)
    }

    /// Find files matching a glob pattern in a directory.
    private func findFiles(in directory: String, matching pattern: String) async throws -> [String] {
        var files: [String] = []

        // Simple pattern matching (not full glob support)
        let hasExtension = pattern.contains(".")

        guard let dirContents = try? FileManager.default.contentsOfDirectory(atPath: directory) else {
            return files
        }

        for file in dirContents {
            var matches = false

            if hasExtension {
                // Match extension
                if let ext = pattern.split(separator: ".").last {
                    matches = file.hasSuffix(".\(ext)")
                }
            } else {
                // Match prefix
                let prefix = pattern.replacingOccurrences(of: "*", with: "")
                matches = file.hasPrefix(prefix)
            }

            if matches {
                files.append(file)
            }
        }

        return files
    }
}
