#!/bin/bash
set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if only models should be downloaded
MODELS_ONLY=false
if [[ "$1" == "--models-only" ]]; then
    MODELS_ONLY=true
fi

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     briefly Setup & Configuration      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to print step header
print_step() {
    echo -e "${BLUE}[$1]${NC} $2"
}

# Function to print success
print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

# Function to print warning
print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

# Function to print error
print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Verify prerequisites
if [ "$MODELS_ONLY" = false ]; then
    print_step "1/5" "Verifying prerequisites..."
    
    if ! command_exists swift; then
        print_error "Swift not found. Please install Xcode Command Line Tools:"
        echo "  xcode-select --install"
        exit 1
    fi
    SWIFT_VERSION=$(swift --version | head -1)
    print_success "Swift found: $SWIFT_VERSION"
    
    if ! command_exists python3; then
        print_error "Python 3 not found. Please install Python 3.8+"
        exit 1
    fi
    PYTHON_VERSION=$(python3 --version)
    print_success "Python found: $PYTHON_VERSION"
    echo ""
fi

# 1. Swift Dependencies
if [ "$MODELS_ONLY" = false ]; then
    print_step "2/5" "Resolving Swift packages..."
    if swift package resolve; then
        print_success "Swift packages resolved"
    else
        print_error "Failed to resolve Swift packages"
        exit 1
    fi
    echo ""
fi

# 2. Python Environment & MLX Setup
if [ "$MODELS_ONLY" = false ]; then
    print_step "3/5" "Setting up Python environment for MLX..."
    
    if [ ! -d ".venv" ]; then
        python3 -m venv .venv
        print_success "Virtual environment created"
    else
        print_success "Virtual environment already exists"
    fi
    
    source .venv/bin/activate
    
    # Upgrade pip
    pip install --upgrade pip --quiet
    
    # Install required packages for MLX and model downloading
    print_success "Installing Python dependencies..."
    pip install --quiet mlx mlx-lm huggingface_hub soundfile numpy
    
    # Check if huggingface-cli is available, if not install it
    if ! command_exists hf; then
        pip install --quiet huggingface_hub[cli]
    fi
    
    print_success "Python dependencies installed"
    echo ""
fi

# 3. Environment Configuration
if [ "$MODELS_ONLY" = false ]; then
    print_step "4/5" "Configuring environment..."
    
    # Load existing .env if it exists
    if [ -f ".env" ]; then
        source .env
        print_success ".env file found"
    else
        print_warning ".env file not found, creating template..."
    fi
    
    # Set HuggingFace token (use provided token or check existing)
    HF_TOKEN="${HUGGINGFACEHUB_API_TOKEN:-${HF_TOKEN:-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}}"
    
    # Update .env file
    {
        echo "# Briefly Configuration"
        echo "# Generated by setup.sh on $(date)"
        echo ""
        echo "# HuggingFace Hub Token (for downloading models)"
        echo "HUGGINGFACEHUB_API_TOKEN=${HF_TOKEN}"
        echo "HF_TOKEN=${HF_TOKEN}"
        echo ""
        echo "# Voice Engine Configuration (default: local MLX models)"
        echo "VOICE_ENGINE=local"
        echo "VOICE_PROFILE=normal"
        echo "STT_PROFILE=parakeet"
        echo ""
        echo "# Local Model Paths"
        echo "KOKORO_MODEL_PATH=$(pwd)/models/kokoro-82m"
        echo "LFM_MODEL_PATH=$(pwd)/models/lfm-2.5-audio"
        echo ""
        echo "# Fallback Configuration (ElevenLabs)"
        if [ -n "${ELEVENLABS_API_KEY:-}" ]; then
            echo "ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}"
        else
            echo "# ELEVENLABS_API_KEY=your-api-key-here"
        fi
        if [ -n "${ELEVENLABS_VOICE_ID:-}" ]; then
            echo "ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}"
        else
            echo "ELEVENLABS_VOICE_ID=21m00Tcm4TlvDq8ikWAM"
        fi
        echo ""
        echo "# Other API Keys (preserve existing if present)"
        if [ -n "${GOOGLE_API_KEY:-}" ]; then
            echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}"
        fi
        if [ -n "${GEMINI_API_KEY:-}" ]; then
            echo "GEMINI_API_KEY=${GEMINI_API_KEY}"
        fi
        if [ -n "${WHOOP_CLIENT_ID:-}" ]; then
            echo "WHOOP_CLIENT_ID=${WHOOP_CLIENT_ID}"
        fi
        if [ -n "${WHOOP_CLIENT_SECRET:-}" ]; then
            echo "WHOOP_CLIENT_SECRET=${WHOOP_CLIENT_SECRET}"
        fi
        if [ -n "${WHOOP_REDIRECT_URI:-}" ]; then
            echo "WHOOP_REDIRECT_URI=${WHOOP_REDIRECT_URI}"
        fi
    } > .env.new
    
    # Merge with existing .env (preserve custom values)
    if [ -f ".env" ]; then
        # Extract existing values that aren't in our template
        grep -E "^[A-Z_]+=" .env | while IFS='=' read -r key value; do
            if ! grep -q "^${key}=" .env.new; then
                echo "${key}=${value}" >> .env.new
            fi
        done
    fi
    
    mv .env.new .env
    print_success "Environment configured (local models as default)"
    echo ""
fi

# 4. Download Models
print_step "$([ "$MODELS_ONLY" = false ] && echo "5/5" || echo "1/1")" "Checking and downloading local MLX models..."

# Activate venv if not already active
if [ -d ".venv" ] && [ -z "${VIRTUAL_ENV:-}" ]; then
    source .venv/bin/activate
fi

# Set HuggingFace token
export HF_TOKEN="${HUGGINGFACEHUB_API_TOKEN:-${HF_TOKEN:-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}}"
export HUGGINGFACEHUB_API_TOKEN="${HF_TOKEN}"

# Login to HuggingFace if token is set
if [ -n "${HF_TOKEN}" ] && [ "${HF_TOKEN}" != "your-token-here" ]; then
    echo "${HF_TOKEN}" | hf login --token "${HF_TOKEN}" 2>/dev/null || true
fi

mkdir -p models

# Helper function to download model if not present
download_model() {
    local repo_id=$1
    local dest_dir=$2
    local model_name=$3
    
    echo ""
    echo -e "${BLUE}📦 Checking ${model_name}...${NC}"
    
    if [ -d "$dest_dir" ] && [ "$(ls -A "$dest_dir" 2>/dev/null)" ]; then
        print_success "${model_name} already exists in $dest_dir"
        return 0
    fi
    
    print_warning "Downloading ${model_name} (this may take a while)..."
    
    # Try using huggingface-cli
    if command_exists hf; then
        if hf download "${repo_id}" --local-dir "${dest_dir}" --local-dir-use-symlinks False 2>&1 | tee /tmp/hf-download.log; then
            print_success "${model_name} downloaded successfully"
            return 0
        else
            print_warning "hf download failed, trying alternative method..."
        fi
    fi
    
    # Fallback: use Python
    python3 << EOF
import os
from huggingface_hub import snapshot_download

try:
    snapshot_download(
        repo_id="${repo_id}",
        local_dir="${dest_dir}",
        local_dir_use_symlinks=False,
        token=os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACEHUB_API_TOKEN")
    )
    print("✅ Download successful")
except Exception as e:
    print(f"❌ Download failed: {e}")
    exit(1)
EOF
    
    if [ $? -eq 0 ]; then
        print_success "${model_name} downloaded successfully"
    else
        print_error "Failed to download ${model_name}"
        echo ""
        echo "Troubleshooting:"
        echo "  1. Check your internet connection"
        echo "  2. Verify HUGGINGFACEHUB_API_TOKEN in .env"
        echo "  3. Try: hf auth login"
        echo "  4. Check available disk space"
        return 1
    fi
}

# Download Kokoro-82M model
download_model "mlx-community/Kokoro-82M-4bit" "models/kokoro-82m" "Kokoro-82M"

# Download LFM 2.5 Audio model
download_model "mlx-community/LFM2.5-Audio-1.5B-6bit" "models/lfm-2.5-audio" "LFM 2.5 Audio"

echo ""
echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     ✅ Setup Complete!                 ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo "  • Run '${BLUE}make build${NC}' to build the project"
echo "  • Run '${BLUE}make brief${NC}' to generate your first brief"
echo "  • Run '${BLUE}make brief-voice${NC}' for voice output (uses local MLX models)"
echo "  • Run '${BLUE}make install${NC}' to install to /usr/local/bin"
echo ""
echo -e "${GREEN}Configuration:${NC}"
echo "  • Local MLX models are set as default (VOICE_ENGINE=local)"
echo "  • Models are located in: $(pwd)/models/"
echo "  • Configuration is in: $(pwd)/.env"
echo ""
echo -e "${YELLOW}Note:${NC} To use cloud voice (ElevenLabs), set VOICE_ENGINE=cloud in .env"
echo ""
